bind_addr = ":8585"
log_level = "debug"

[collect]
data_folder = "."

[casher]
storage_time = 30

[systems]

[systems.sms]
len_sms= 4

[systems.voice]
len_voice = 8

[systems.email]
len_email = 3

[systems.mms]
mms_req = "http://127.0.0.1:8383/mms"
len_mms = 4

[systems.incident]
incident_req = "http://127.0.0.1:8383/accendent"

[systems.support]
support_req = "http://127.0.0.1:8383/support"
support_pers = 7
ticket_per_hour = 18
